cache: bundler

language:
  - ruby

rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.3

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile

#branches:
#  only:
#    - master

sudo: false

#script: bundle exec rspec --color --format documentation
